### ISSUE TITLE
Redmi Note 10S - Home - Clicking "Go Back" button leads to error page

### ISSUE THREAD

**Issue by manirolo** [mkandan1/mkandan1.github.io#11]
Steps to recreate:
1. Go to https://www.mkandan.com/page
2. Click "Go back" button.

Expected Result:
It should be redirected to Home page of mkandan.com

Actual Result:
It has redirected to error page

Additional Info:
Error: Your connection is not private

I didn't try it on desktop.

**Comment by manirolo** [comment]
Bug fix has been started on 18.12.2021 10:55 PM

**Comment by themani-23** [comment]
### Bug fix verification:

BFV started on: 18.12.2021 11:34 PM

BFV ended on: 18.12.2021 11:35 PM

### Result:

Fixed
