### ISSUE TITLE
Redmi Note 10S - 404 Error Page - Should be "Return to Home Page" instead of "Go back"

### ISSUE THREAD

**Issue by manirolo** [mkandan1/mkandan1.github.io#12]
Steps to recreate:
1. Go to https://www.mkandan.com/page

Excepted Result:
It should be "Return to Home Page" instead of "Go back".

Actual Result:
"Go back" text present.

Additional Info:

Windows 10

**Comment by manirolo** [comment]
Bug fix started on 18.12.2021 11:04 PM

**Comment by themani-23** [comment]
### Bug fix verification:
BFV started on: 18.12.2021 11:36 PM

BFV ended on: 18.12.2021 11:37 PM

### Result:
Fixed
