### ISSUE TITLE
Windows 10 - Home - Dark mode can enable or off when click on near dark mode button

### ISSUE THREAD

**Issue by manirolo** [mkandan1/mkandan1.github.io#8]
Steps to recreate the issue
 1. Open https://www.mkandan.com/
 2. Click on the near/around dark mode button.

Expected Result

The dark mode should not be enabled/off when clicking on the near/around the dark mode button.

**Comment by mkandan1** [comment]
Start Time: 11:52 AM, 08-08-2021(DD-MM-YYYY)

**Comment by manirolo** [comment]
Great!

**Comment by themani-23** [comment]
Thank you! Great work today guys. See you all tomorrow.
